Repository alaniscrln/bookingCalendarJS, pull requests merged in 2021-05, with the labels that each got.

#2 Folders structure reorganized
  src/app/Controller/Calendar.ts
  src/app/Pipes/Language.ts
  src/app/Services/ApiCalendar.ts
  src/app/Views/BookingCalendar.ts
  src/app/Views/BookingList.ts
  src/index.ts
Labels: enhancement

#5 Refactor BookingCalendar class
  src/app/Views/BookingCalendar.ts
Labels: documentation

#6 selectedDay function fixed and refactor setBookingList function
  src/app/Views/BookingCalendar.ts
  src/app/Views/BookingList.ts
Labels: documentation, enhancement
